# 0828

## 예외처리(Exception handling)

### 프로그램 오류

#### 컴파일 에러(compile-time error)와 런타임 에러(runtime error)

- 컴파일 에러 – 컴파일할 때 발생하는 에러
- 런타임 에러 – 실행할 때 발생하는 에러

#### Java의 런타임 에러 – 에러(error)와 예외(exception)
 
```
에러(error) - 프로그램 코드에 의해서 수습될 수 없는 심각한 오류
예외(exception) - 프로그램 코드에 의해서 수숩될 수 있는 다소 미약한 오류
```

### 에러(error)는 어쩔 수 없지만, 예외(exception)는 처리해야 한다

```
에러(error) `- 프로그램 코드에 의해서 수습될 수 없는 심각한 오류
예외(exception) - 프로그램 코드에 의해서 수습될 수 있는 다소 미약한 오류
```

### 예외처리의 정의와 목적

```
예외처리(exception handlng)
정의 - 프로그샘 실행 시 발생할 수 있는 예외의 발생에 대비한 코드를 작성하는 것
목적 - 프로그램의 비정상 종료를 막고, 정상적인 실행상태를 유지하는 것
```

### 예외처리구문 - try - catch

```
try{
	// 예외가 여기 발생할 가능성이 있는 문장들을 넣기,
		
		} catch (Exctption e1) {
		// Exception1이 발생했을 경우, 이를 처리하기 위한 문장 작성
		} catch (Exctption e2) {
		// Exception2이 발생했을 경우, 이를 처리하기 위한 문장 작성
		} ....
		catch (Exctption eN) {
		// ExceptionN이 발생했을 경우, 이를 처리하기 위한 문장 작성
		}
```

### try-catch문에서의 흐름

- try블럭 내에서 예외가 발생한 경우.

1. 발생한 예외와 일치하는 catch블럭이 있는지 확인
2. 일치하는 cathc블럭을 찾게 되면, 그 catch블럭 내의 문장들을 수행하고 전체 try-cathc문을 빠져나가서 그 다음 문장을 계속해서 수행한다. 만일 일치하는 catch블럭을 찾지 못 하면, 예외는 처리되지 못한다.

- try블럭 내에서 예외가 발생하지 않은 경우.

1. catch블럭을 거치지 않고 전체 try-catch문을 빠져나가서 수행을 계속한다.


### 예외 발생시키기

1. 먼저 연산자 new를 이용해서 발생시키려는 예외 클래스의 객체를 만든 다음
2. 키워드 throw를 이용해서 예외를 발생시킨다.

```
Exception e = new Exception("고의로 발생"); // (1)
thorw e; // (2)
```

### 예외 클래스의 계층구조

- 예외 클래스는 크게 두 그룹으로 나뉜다

```
RuntimeException클래스들 - 프로그래머의 실수로 발생하는 예외 <- 예외처리 필수
Exception 클래스들 - 사용자의 실수와 같은 외적인 요인에 의해 발생하는 예외 <- 예외처리 선택
```

<img src= "https://github.com/happiipark/Java/assets/124240328/c77c1515-ce34-4536-96ee-21f4bafc6baa" width="700" height ="400" />